sudo: required

language: bash

before_install:
  - chmod +x cronjob.sh

#install:
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin //NEED TO LOG IN GIT FOR CHANGELOG

script:
  - ./cronjob.sh
